### ISSUE TITLE
Featherweight Generic Go prototype not publicly available

### ISSUE THREAD

**Issue by puffnfresh** [wenkokke/featherweight-go-gen#1]
The `fgg` function uses a Go library called `github.com/rhu1/fgg` but this repository is unavailable. Maybe it is not public.

**Comment by wenkokke** [comment]
Yes, this is intentional. This library is meant to test *any* Featherweight Generic Go implementation, not just ours. We have chosen not to release our prototype to the public to avoid confusion with the Go Team's prototype.

Of course, I've only used it to test *our* prototype, hence that command is still hardcoded in. So I'll take this as a bug report pointing out that I should generalise the main program to let you to pass in the FGG command.

If you would still like to run the test suite for our prototype, you can request a copy.

**Comment by puffnfresh** [comment]
The repository is now available: https://github.com/rhu1/fgg
